#pragma once

namespace input {
enum Key {
    A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
    N0, N1, N2, N3, N4, N5, N6, N7, N8, N9,
    LeftShift,
    RightShift,
    LeftControl,
    RightControl,
    LeftAlt,
    RightAlt,
    F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12,
    Escape,
    Enter,
    Backspace,
    Grave,
    Space,
    Comma,
    Period,
    ForwardSlash,
    BackSlash,
    SemiColon,
    Apostrophe,
    LeftAngle,
    RightAngle,
    LeftSquareBracket,
    RightSquareBracket,
    LeftCurly,
    RightCurly,
    Tab,
    Minus,
    Plus,
    Up,
    Down,
    Left,
    Right,
    Unknown
};
}
